import type { Translation } from "../translate";

/**
 * Traducerea în engleză a chestionarului „Consimțământ informat".
 * Cheile sunt textele românești exacte din șablon; un text românesc schimbat
 * fără traducere apare netradus (verificat de `untranslated`).
 */
export const consimtamantEn: Translation = {
  strings: {
    "Formular de informare și consimțământ al pacientului informat privind tratamentul stomatologic":
      "Information and informed consent form for dental treatment",
    "Consimțământ informat":
      "Informed consent",
    "Nume și prenume pacient":
      "Patient's full name",
    "CNP":
      "Personal numeric code (CNP)",
    "Sunt de acord ca echipa medicală":
      "I agree that the medical team",
    "…să efectueze examinarea, diagnosticele, recomandările și actele medicale necesare în cazul meu.":
      "…may carry out the examination, diagnoses, recommendations and medical procedures necessary in my case.",
    "Etapele necesare pentru tratarea afecțiunii(lor) mele stomatologice mi-au fost explicate și includ: obturații, lucrări protetice fixe, radiografii, extracții, tratamente endodontice, tratament parodontal, proteze mobilizabile, tratament ortodontic, altele.":
      "The steps needed to treat my dental condition(s) have been explained to me and include: fillings, fixed prosthetic work, X-rays, extractions, root canal treatment, periodontal treatment, removable dentures, orthodontic treatment, other.",
    "Am fost informat cu privire la diagnosticul afecțiunilor mele dentare, la alternativele de tratament ale acestor afecțiuni (dacă ele există), precum și la consecințele neintervenției terapeutice. Am înțeles că există riscuri inerente și potențiale pentru orice plan de tratament sau intervenție terapeutică. Deși nu apar în mod obișnuit, aceste riscuri se pot manifesta, după cum urmează:":
      "I have been informed about the diagnosis of my dental conditions, the treatment alternatives for these conditions (where they exist), and the consequences of not treating them. I understand that there are inherent and potential risks in any treatment plan or procedure. Although they do not usually occur, these risks may arise as follows:",
    "Radiografii":
      "X-rays",
    "Pentru precizarea diagnosticului și stabilirea planului de tratament pot fi necesare serii repetate de radiografii sau alte metode de investigare imagistică (tomografie computerizată, teleradiografie de profil, repetarea examenului radiologic în diferite incidențe). Refuzul de a face aceste radiografii sau investigații imagistice poate avea consecințe negative asupra rezultatului final, mergând până la eșecul tratamentului. În timpul tratamentului pot apărea informații diagnostice neprevăzute, care să extindă amploarea și/sau tipul intervențiilor. Sunt de acord ca echipa medicală menționată anterior să realizeze și intervențiile neprevăzute în momentul inițierii tratamentului.":
      "To establish the diagnosis and the treatment plan, repeated series of X-rays or other imaging methods may be needed (computed tomography, lateral cephalometric radiograph, repeated X-rays from different angles). Refusing these X-rays or imaging investigations may have negative consequences for the final result, up to and including treatment failure. During treatment, unforeseen diagnostic information may arise that extends the scope and/or type of the procedures. I agree that the medical team mentioned above may also carry out procedures unforeseen at the start of treatment.",
    "Schimbări în planul de tratament":
      "Changes to the treatment plan",
    "Am înțeles că în timpul procedurilor terapeutice planificate pot apărea informații diagnostice neprevăzute, care să extindă amploarea și/sau timpul intervenției(ilor). Autorizez prin aceasta persoana(ele) prevăzută(e) la paragraful 1 să realizeze și intervențiile neprevăzute în momentul inițierii tratamentului.":
      "I understand that during the planned procedures unforeseen diagnostic information may arise that extends the scope and/or duration of the procedure(s). I hereby authorise the person(s) named in paragraph 1 to also carry out procedures unforeseen at the start of treatment.",
    "Medicamentație":
      "Medication",
    "Anestezicele, antibioticele sau alte medicamente și substanțe pot cauza diverse reacții alergice care se pot manifesta prin, fără a se limita la: eritem (roșeață), tumefacții (umflături), dureri, până la șoc anafilactic.":
      "Anaesthetics, antibiotics or other medicines and substances can cause various allergic reactions, which may include, but are not limited to: erythema (redness), swelling, pain, up to anaphylactic shock.",
    "Am informat medicul asupra faptului că sunt alergic(ă) la următoarele substanțe":
      "I have informed the doctor that I am allergic to the following substances",
    "Consimt la administrarea anestezicelor necesare.":
      "I consent to the administration of the necessary anaesthetics.",
    "Anestezia":
      "Anaesthesia",
    "După anestezie poate apărea, fără a se limita la: reducerea sau pierderea sensibilității dinților vecini, a buzelor, limbii și a țesuturilor înconjurătoare (parestezie/anestezie) pe o perioadă nedeterminată de timp, apariția temporară a unui hematom local, zonă ușor dureroasă la locul de injecție, tumefacție (umflătură) temporară a obrazului sau a țesuturilor înconjurătoare.":
      "After anaesthesia the following may occur, including but not limited to: reduced or lost sensation in neighbouring teeth, lips, tongue and surrounding tissues (paraesthesia/anaesthesia) for an indefinite period, a temporary local haematoma, a slightly painful area at the injection site, temporary swelling of the cheek or surrounding tissues.",
    "Obturații (plombe)":
      "Fillings",
    "Realizarea sau înlocuirea obturațiilor pot produce – fără a se limita la: hipersensibilitate temporară a dintelui, inflamație a pulpei dentare cu necesitatea ulterioară a tratamentului endodontic (de canal), apariția unor fisuri/fracturi ale smalțului dentar, longevitate mai redusă a restaurărilor în raport cu cele precedente. În timp, obturațiile estetice își pot modifica culoarea din cauza alimentelor colorate, a fumatului etc.":
      "Placing or replacing fillings may cause, including but not limited to: temporary sensitivity of the tooth, inflammation of the dental pulp requiring later root canal treatment, cracks/fractures of the enamel, and shorter longevity of the restorations compared with the previous ones. Over time, tooth-coloured fillings may change colour because of coloured foods, smoking etc.",
    "Tratamentul endodontic (de canal)":
      "Root canal (endodontic) treatment",
    "Tratamentul de canal nu garantează salvarea dintelui și există situații în care, în ciuda tuturor eforturilor depuse pentru salvarea dintelui, acesta trebuie extras. Alternativele tratamentului de canal sunt reprezentate de extracția dintelui sau nonintervenție. Este obligatorie finalizarea tratamentului endodontic. În timpul sau după efectuarea tratamentului de canal pot apărea următoarele, fără a se limita la: durere, tumefacție (umflătură), infecție, reinfecție, iritarea sau lezarea mucoasei bucale înconjurătoare, afectare parodontală (pierderea suportului osos și mobilizarea dintelui ca urmare a infecției), ruperea unor instrumente (cum ar fi acele de canal) în interiorul rădăcinii dintelui, perforația coroanei sau a rădăcinii dintelui. Rata de succes a tratamentului endodontic este de 85-95% și uneori tratamentul endodontic trebuie repetat sau/și pot fi necesare mici intervenții chirurgicale asupra dintelui respectiv, sau poate fi necesară reluarea tratamentului. Tratamentul de canal poate necesita uneori mai multe ședințe pentru a fi finalizat. De asemenea, tratamentul de canal poate determina colorarea dintelui și o susceptibilitate mai mare la fractură a dintelui; de aceea este obligatoriu ca după finalizarea tratamentului endodontic dintele să primească o restaurare definitivă: obturație sau coroană.":
      "Root canal treatment does not guarantee that the tooth will be saved, and there are situations in which, despite every effort, the tooth must be extracted. The alternatives to root canal treatment are extraction of the tooth or no treatment. Root canal treatment must be completed. During or after root canal treatment the following may occur, including but not limited to: pain, swelling, infection, reinfection, irritation or injury of the surrounding oral mucosa, periodontal damage (loss of bone support and loosening of the tooth due to infection), breakage of instruments (such as root canal files) inside the root, perforation of the crown or root. The success rate of root canal treatment is 85–95%; sometimes the treatment must be repeated and/or minor surgery on the tooth may be needed, or the treatment may need to be redone. Root canal treatment can sometimes take several appointments to complete. Root canal treatment may also cause discolouration of the tooth and make it more prone to fracture; therefore, after root canal treatment is completed, the tooth must receive a definitive restoration: a filling or a crown.",
    "Tratamentul de albire":
      "Tooth whitening",
    "După tratamentul de albire este posibil ca dinții să prezinte hipersensibilitate persistentă. În timpul și după tratamentul de albire este posibilă apariția sensibilității/leziunilor la nivelul gingiei. Intensitatea și durata efectului de albire sunt variabile.":
      "After whitening, the teeth may show persistent sensitivity. During and after whitening, sensitivity or lesions of the gums may occur. The intensity and duration of the whitening effect vary.",
    "Extracția dentară":
      "Tooth extraction",
    "După extracția dentară poate apărea, prin afectarea nervilor din vecinătate, fără a se limita la: reducerea/pierderea sensibilității dinților vecini, a buzelor, limbii și a țesuturilor înconjurătoare (parestezie/anestezie) pe o perioadă nedeterminată de timp.":
      "After a tooth extraction, damage to nearby nerves may cause, including but not limited to: reduced/lost sensation in neighbouring teeth, lips, tongue and surrounding tissues (paraesthesia/anaesthesia) for an indefinite period.",
    "Riscurile pe care le presupune extracția dentară pot fi, fără a se limita la: durere, tumefacție (umflătură), învinețire, alveolită (infecție), vindecare întârziată, afectarea dinților și a restaurărilor din vecinătate sau de pe arcada antagonistă, deschiderea sinusurilor maxilare, a foselor nazale, fractura rădăcinilor și împingerea lor în sinusul maxilar, în fosele nazale sau în spațiile înconjurătoare, în canalul mandibular sau în gaura mentală, aspirarea și/sau înghițirea de corpi străini, spasme musculare locale, fractura maxilarului sau a mandibulei, afectarea nervilor din vecinătate cu reducerea/pierderea sensibilității dinților vecini, a buzelor, limbii și a țesuturilor înconjurătoare (parestezie/anestezie) pe o perioadă nedeterminată de timp, lezarea unor vase de sânge de vecinătate: arteră alveolară, maxilară, palatină sau ramuri mucozale sau intraosoase ale acestora. Am înțeles că în cazul accidentelor din timpul anesteziei, a complicațiilor intraoperatorii, accidentelor și incidentelor postextracționale poate apărea necesitatea unui tratament de specialitate la un medic chirurg maxilo-facial, tratament de specialitate al cărui cost intră în responsabilitatea mea.":
      "The risks of tooth extraction may include, but are not limited to: pain, swelling, bruising, dry socket (alveolitis, infection), delayed healing, damage to neighbouring teeth and restorations or to those in the opposing arch, opening of the maxillary sinuses or nasal cavities, fracture of the roots and their displacement into the maxillary sinus, nasal cavities or surrounding spaces, the mandibular canal or the mental foramen, inhalation and/or swallowing of foreign bodies, local muscle spasm, fracture of the upper or lower jaw, damage to nearby nerves with reduced/lost sensation in neighbouring teeth, lips, tongue and surrounding tissues (paraesthesia/anaesthesia) for an indefinite period, injury to nearby blood vessels: the alveolar, maxillary or palatine artery or their mucosal or intraosseous branches. I understand that in the event of accidents during anaesthesia, complications during surgery, or accidents and incidents after the extraction, specialist treatment by an oral and maxillofacial surgeon may be needed, and that the cost of this specialist treatment is my responsibility.",
    "Boala parodontală":
      "Periodontal (gum) disease",
    "Problemele parodontale manifestate prin afectarea gingiei și a osului adiacent pot duce la pierderea mai rapidă a dinților, lucrărilor protetice și implanturilor. Planul de tratament mi-a fost explicat și cuprinde: un program de întreținere/dispensarizare, intervenții de scaling, chiuretaj gingival și planare radiculară și în unele cazuri intervenții parodontale, inclusiv chirurgicale, asupra dinților, gingiei și osului, adiție osoasă și/sau extracții. Absența intervenției poate agrava starea de sănătate parodontală.":
      "Periodontal problems, affecting the gums and the adjacent bone, can lead to faster loss of teeth, prosthetic work and implants. The treatment plan has been explained to me and includes: a maintenance/follow-up programme, scaling, gingival curettage and root planing and, in some cases, periodontal procedures, including surgery, on the teeth, gums and bone, bone grafting and/or extractions. Not treating the condition may worsen periodontal health.",
    "Scaling, chiuretaj gingival, planare radiculară":
      "Scaling, gingival curettage, root planing",
    "După intervențiile de scaling, chiuretaj gingival și planare radiculară, dinții vor avea o mobilitate inițial crescută iar gingiile se vor retrage. Rădăcinile dentare astfel expuse vor fi mai sensibile. De obicei, hipermobilitatea și hipersensibilitatea se remit spontan în circa șase luni, însă pot necesita tratament suplimentar. Rădăcinile expuse au o structură mai poroasă decât smalțul dinților și sunt astfel mai susceptibile la retenția alimentelor și colorație decât restul suprafețelor dentare. Retracția gingivală din zona frontală maxilară poate duce la modificări de fonație care pot necesita intervenție terapeutică suplimentară.":
      "After scaling, gingival curettage and root planing, the teeth will initially be more mobile and the gums will recede. The roots exposed in this way will be more sensitive. Usually the increased mobility and sensitivity resolve on their own within about six months, but further treatment may be needed. Exposed roots are more porous than tooth enamel and therefore more prone to food retention and staining than the rest of the tooth surfaces. Gum recession in the upper front area can cause changes in speech that may require further treatment.",
    "După intervențiile de scaling, chiuretaj gingival și planare radiculară este necesară o reevaluare diagnostică, în urma căreia pot fi recomandate și alte intervenții parodontale.":
      "After scaling, gingival curettage and root planing, a diagnostic re-evaluation is needed, after which further periodontal procedures may be recommended.",
    "Intervenții chirurgicale parodontale":
      "Periodontal surgery",
    "Intervențiile parodontale sunt indicate în cazul persistenței pungilor parodontale/infecției. Aceste intervenții au ca scop reducerea/eliminarea pungilor parodontale patologice și curățarea riguroasă a suprafețelor radiculare. Însă, există situații în care după tratament parodontal, din cauza unor factori cum ar fi faza avansată a bolii parodontale, absența unui program susținut de întreținere/dispensarizare, factori nutriționali, endocrini, afecțiuni generale etc., problemele parodontale pot persista sau chiar se pot agrava, mergând până la pierderea dinților.":
      "Periodontal procedures are indicated when periodontal pockets or infection persist. They aim to reduce or eliminate pathological periodontal pockets and to thoroughly clean the root surfaces. However, there are situations in which, after periodontal treatment, because of factors such as an advanced stage of periodontal disease, the lack of a sustained maintenance/follow-up programme, nutritional or endocrine factors, general illnesses etc., the periodontal problems may persist or even worsen, up to the loss of teeth.",
    "Lucrări protetice":
      "Prosthetic work",
    "Lucrări protetice fixe":
      "Fixed prosthetic work",
    "Pentru aplicarea lucrărilor protetice fixe este necesară prepararea (șlefuirea) dinților sau este necesară inserția implanturilor dentare (atunci când agregarea se face pe implanturi). Este foarte important să se respecte programările pentru probe în diverse etape de lucru și pentru cimentarea finală, deoarece întârzierile pot duce la afectarea integrității dinților șlefuiți, a bonturilor implantare și/sau a implantelor, și la alte modificări ce pot necesita refacerea lucrărilor protetice și/sau a implantelor, cu costuri adiționale care cad în responsabilitatea pacientului.":
      "Fixed prosthetic work requires preparation (reshaping) of the teeth or placement of dental implants (when the work is supported by implants). It is very important to keep the appointments for try-ins at the various stages and for final cementation, because delays can damage the prepared teeth, the implant abutments and/or the implants, and cause other changes that may require the prosthetic work and/or implants to be redone, at additional cost to the patient.",
    "După cimentarea fațetelor/coroanelor/punților poate apărea sensibilitate la nivelul dinților pe care acestea sunt aplicate, sau la nivelul porțiunii gingivale din zona corpului de punte.":
      "After veneers, crowns or bridges are cemented, the teeth they are placed on, or the gum area under the bridge, may become sensitive.",
    "Ceramica dentară (porțelanul) este casantă; acrilatul dentar sau compozitul dentar se pot desprinde (fațete sau suprafețe întregi). Fațetele/coroanele din ceramică, zirconiu sau compozit, fără suport metalic, sunt restaurări fragile, care se pot fisura sau fractura relativ ușor, chiar în cazurile în care sunt corect concepute și realizate.":
      "Dental ceramic (porcelain) is brittle; dental acrylic or composite may chip off (veneers or whole surfaces). Ceramic, zirconia or composite veneers and crowns without a metal framework are fragile restorations that can crack or fracture relatively easily, even when correctly designed and made.",
    "Proteze mobilizabile":
      "Removable dentures",
    "Purtarea unei proteze mobilizabile poate fi dificilă. Pot apărea zone dureroase persistente, modificări de fonație (vorbire) și dificultăți în masticație. Eficiența unei proteze totale este de aproximativ 30% față de eficiența unei arcade dentare integre. Protezarea imediată (plasarea protezei imediat după extracțiile dinților) poate fi dureroasă. Protezarea imediată necesită ajustări, căptușiri și rebazări. De asemenea, sunt necesare căptușiri sau rebazări ale protezelor la anumite intervale de timp. Este responsabilitatea pacientului de a respecta programarea pentru ședința de aplicare a protezei/protezelor mobilizabile pe câmpul protetic, deoarece întârzierile pot necesita refacerea protezei/protezelor și/sau a implantelor de sprijin (atunci când agregarea se face pe implanturi) cu costuri adiționale care intră în responsabilitatea pacientului.":
      "Wearing a removable denture can be difficult. Persistent sore spots, changes in speech and difficulty chewing may occur. A complete denture is about 30% as efficient as a full natural dentition. Immediate dentures (placed right after the teeth are extracted) can be painful. Immediate dentures require adjustments, relines and rebases. Dentures also need relining or rebasing at certain intervals. It is the patient's responsibility to keep the appointment for fitting the removable denture(s), because delays may require the denture(s) and/or the supporting implants (when the denture is implant-supported) to be redone, at additional cost to the patient.",
    "După cimentarea lucrărilor fixe și după aplicarea în cavitatea bucală a protezelor mobilizabile se recomandă: NU se va mușca din fructe (mere etc.); orice necesită „mușcătură” trebuie tăiat în bucăți mai mici; NU se vor zdrobi miezi de nucă, alune, boabe de cafea, oase din mâncare, sâmburi sau orice alte alimente dure sau lemnoase, protezele putându-se mișca din cauza forțelor masticatorii mari; NU se va încerca perforarea / desfacerea / tăierea / ruperea / tracționarea cu lucrările, sau cu orice alt dinte cu care lucrările intră în contact, a capacelor de sticle, ambalajelor alimentare sau nealimentare, foliilor de orice tip sau a altor materiale de uzanță zilnică; NU vor fi ținute cu lucrările obiecte dure; NU se practică sporturi agresive.":
      "After fixed work is cemented and after removable dentures are fitted, it is recommended that you: do NOT bite into fruit (apples etc.); anything that needs to be bitten should be cut into smaller pieces; do NOT crack nuts, hazelnuts, coffee beans, bones, fruit stones or any other hard or woody foods, as the prostheses may move because of the high chewing forces; do NOT try to pierce, open, cut, tear or pull bottle caps, food or non-food packaging, foils of any kind or other everyday materials with the prosthetic work or with any tooth it touches; do NOT hold hard objects with the prosthetic work; do NOT practise aggressive sports.",
    "Orice modificare a integrității lucrărilor protetice fixe sau mobilizabile trebuie anunțată în cel mai scurt timp echipei medicale, pentru a putea minimiza efectele asupra dinților pe care se ancorează, dar și asupra celorlalți dinți și lucrări și asupra țesuturilor moi înconjurătoare, sau asupra implantelor existente la nivelul cavității orale.":
      "Any damage to fixed or removable prosthetic work must be reported to the medical team as soon as possible, to minimise the effects on the teeth it is anchored to, on the other teeth and restorations, on the surrounding soft tissues, and on any implants in the mouth.",
    "Nicio formă de protezare fixă sau mobilizabilă nu este definitivă, orice piesă protetică necesitând la un moment dat ajustare sau refacere (în aceeași formă sau în formă nouă) în funcție de evoluția oaselor maxilare, a edentațiilor, a mucoasei și a gingiei acoperitoare, a uzurii normale a dinților protezelor, a modificărilor suferite de implantele inserate, sau a modificării lucrărilor protetice fixe sau mobilizabile existente.":
      "No form of fixed or removable prosthetic work is permanent; every prosthesis will at some point need adjustment or remaking (in the same or a new form), depending on changes in the jaw bones, missing teeth, the covering mucosa and gums, normal wear of the denture teeth, changes affecting the implants, or changes to existing fixed or removable prosthetic work.",
    "Bruxismul, alte parafuncții ocluzale":
      "Bruxism and other parafunctional habits",
    "Obiceiurile nefuncționale care determină suprasolicitarea arcadelor dentare, cum ar fi: bruxismul (scrâșnitul dinților), încleștarea maxilarelor, onicofagia (roaderea unghiilor) etc., pot determina pierderea prematură a restaurărilor dentare, a protezelor mobilizabile, a implantelor, uzură patologică/fisuri/fracturi ale dinților naturali, uzură accentuată/fisuri/fracturi ale dinților sau ale bazelor protezelor fixe sau mobilizabile, modificarea structurilor de suport – rezorbții osoase sau boselarea proceselor alveolare, anchiloza rădăcinilor sau a implantelor, parodontite/periimplantite, hipercalcificări ale canalelor radiculare și mobilizarea dinților sau a implantelor existente.":
      "Non-functional habits that overload the dental arches, such as bruxism (teeth grinding), jaw clenching, nail biting (onychophagia) etc., can lead to premature loss of dental restorations, removable dentures and implants; pathological wear, cracks or fractures of natural teeth; marked wear, cracks or fractures of the teeth or bases of fixed or removable prostheses; changes in the supporting structures – bone resorption or bulging of the alveolar processes, ankylosis of roots or implants, periodontitis/peri-implantitis, hypercalcification of root canals, and loosening of existing teeth or implants.",
    "Întreținerea și dispensarizarea":
      "Maintenance and regular check-ups",
    "Pentru a asigura funcționalitatea și longevitatea restaurărilor stomatologice, a dinților și a țesuturilor de suport ale acestora este necesar ca pacientul să se prezinte de cel puțin două ori pe an pentru control, igienizare profesională, precum și pentru remedierea precoce a eventualelor probleme apărute. Nerespectarea acestor reguli poate determina eșecul prematur al tratamentelor, cu apariția unor complicații locale sau la distanță.":
      "To ensure the function and longevity of dental restorations, of the teeth and of their supporting tissues, the patient needs to attend at least twice a year for a check-up, professional cleaning and early treatment of any problems. Not following these rules can lead to early failure of treatment, with local or distant complications.",
    "Sunt pe deplin de acord cu recomandările medicului / echipei medicale în îngrijirea căruia / căreia mă aflu, înțelegând că nerespectarea acestor recomandări poate duce la un rezultat final mai puțin decât optim sau chiar la eșecul tratamentului.":
      "I fully agree with the recommendations of the doctor / medical team in whose care I am, understanding that not following these recommendations may lead to a less than optimal result or even to treatment failure.",
    "Declar că mi-au fost furnizate informații legate de serviciile medicale disponibile, despre starea mea de sănătate, diagnostic, prognostic, natura și scopul tratamentului propus, intervențiile și strategia terapeutică propuse, riscurile și consecințele tratamentului, alternativele viabile de tratament, riscurile potențiale, riscurile neefectuării tratamentului, riscurile nerespectării recomandărilor medicale și costul estimativ al tratamentului.":
      "I declare that I have been given information about the medical services available, my state of health, diagnosis, prognosis, the nature and purpose of the proposed treatment, the proposed procedures and treatment strategy, the risks and consequences of treatment, viable treatment alternatives, potential risks, the risks of not having the treatment, the risks of not following medical advice, and the estimated cost of treatment.",
    "Sunt de acord cu recoltarea, păstrarea și folosirea produselor biologice.":
      "I agree to the collection, storage and use of biological samples.",
    "Am fost înștiințat de dreptul la o a doua opinie medicală.":
      "I have been informed of my right to a second medical opinion.",
    "Am avut oportunitatea să pun întrebările pe care le-am dorit privind planul de tratament și tuturor întrebărilor li s-a răspuns satisfăcător.":
      "I have had the opportunity to ask any questions I wished about the treatment plan, and all my questions have been answered satisfactorily.",
    "Certific că știu să scriu și să citesc în limba română și că am înțeles în totalitate acest text.":
      "I certify that I can read and write in English and that I have fully understood this text.",
    "Declar că am înțeles toate informațiile furnizate mai sus de către echipa medicală enumerată anterior, că am prezentat echipei medicale doar informații adevărate și îmi exprim consimțământul informat pentru efectuarea actelor medicale.":
      "I declare that I have understood all the information provided above by the medical team named above, that I have given the medical team only true information, and I give my informed consent to the medical procedures.",
    "Pacient":
      "Patient",
  },
};
